# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171219_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='images'),
        ),
    ]
