# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='media'),
        ),
    ]
